/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Agenda;
import model.AgendaManager;
import javax.swing.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author Dimas
 */
public class EditAgendaDialog extends javax.swing.JDialog {
    private Agenda agenda;
    /**
     * Creates new form TambahAgendaDialog
     */
    public EditAgendaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.agenda = agenda;
        initComponents();
        loadData();
        // Event Handlers
        btnUpdate.addActionListener(e -> updateAgenda());
        btnBatal.addActionListener(e -> dispose());
    }

    EditAgendaDialog(MainFrame aThis, boolean b, Agenda agenda) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        lblDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        lblTanggal = new javax.swing.JLabel();
        spinnerTanggal = new javax.swing.JSpinner();
        lblKategori = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        lblPrioritas = new javax.swing.JLabel();
        cmbPrioritas = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        chkSelesai = new javax.swing.JCheckBox();
        buttonPanelDialog = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Agenda Baru");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(15, 15));

        titlePanel.setBackground(new java.awt.Color(52, 152, 219));
        titlePanel.setPreferredSize(new java.awt.Dimension(400, 60));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("EDIT AGENDA BARU");
        titlePanel.add(lblTitle);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudul.setText("Judul Agenda :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formPanel.add(lblJudul, gridBagConstraints);

        txtJudul.setColumns(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        formPanel.add(txtJudul, gridBagConstraints);

        lblDeskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDeskripsi.setText("Deskripsi :");
        lblDeskripsi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formPanel.add(lblDeskripsi, gridBagConstraints);

        txtDeskripsi.setColumns(25);
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setRows(4);
        txtDeskripsi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDeskripsi);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        formPanel.add(jScrollPane1, gridBagConstraints);

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTanggal.setText("Tanggal :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formPanel.add(lblTanggal, gridBagConstraints);

        spinnerTanggal.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        formPanel.add(spinnerTanggal, gridBagConstraints);

        lblKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKategori.setText("Kategori :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formPanel.add(lblKategori, gridBagConstraints);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kerja", "Kuliah", "personal", "Kesehatan" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        formPanel.add(cmbKategori, gridBagConstraints);

        lblPrioritas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrioritas.setText("Prioritas :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formPanel.add(lblPrioritas, gridBagConstraints);

        cmbPrioritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tinggi", "Sedang", "Rendah" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        formPanel.add(cmbPrioritas, gridBagConstraints);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setText("Status :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formPanel.add(lblStatus, gridBagConstraints);

        chkSelesai.setText("Tandai sebagai selesai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        formPanel.add(chkSelesai, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        buttonPanelDialog.setPreferredSize(new java.awt.Dimension(0, 70));

        btnSimpan.setBackground(new java.awt.Color(39, 174, 96));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setPreferredSize(new java.awt.Dimension(120, 40));
        buttonPanelDialog.add(btnSimpan);

        btnBatal.setBackground(new java.awt.Color(149, 165, 166));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(120, 40));
        buttonPanelDialog.add(btnBatal);

        btnUpdate.setBackground(new java.awt.Color(52, 152, 219));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(120, 40));
        buttonPanelDialog.add(btnUpdate);

        getContentPane().add(buttonPanelDialog, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() {
        txtJudul.setText(agenda.getJudul());
        txtDeskripsi.setText(agenda.getDeskripsi());
        
        Date date = Date.from(agenda.getTanggal().atStartOfDay(ZoneId.systemDefault()).toInstant());
        spinnerTanggal.setValue(date);
        
        cmbKategori.setSelectedItem(agenda.getKategori());
        cmbPrioritas.setSelectedItem(agenda.getPrioritas());
        chkSelesai.setSelected(agenda.isSelesai());
    }
    
    private void updateAgenda() {
        String judul = txtJudul.getText().trim();
        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul tidak boleh kosong!");
            return;
        }
        
        String deskripsi = txtDeskripsi.getText().trim();
        java.util.Date date = (java.util.Date) spinnerTanggal.getValue();
        LocalDate tanggal = LocalDate.ofInstant(date.toInstant(), java.time.ZoneId.systemDefault());
        String kategori = cmbKategori.getSelectedItem().toString();
        String prioritas = cmbPrioritas.getSelectedItem().toString();
        boolean selesai = chkSelesai.isSelected();
        
        Agenda agendaBaru = new Agenda(judul, deskripsi, tanggal, kategori, prioritas);
        agendaBaru.setSelesai(selesai);
        
        AgendaManager.getInstance().updateAgenda(agenda.getId(), agendaBaru);
        
        JOptionPane.showMessageDialog(this, "Agenda berhasil diupdate!");
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAgendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAgendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAgendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAgendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditAgendaDialog dialog = new EditAgendaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel buttonPanelDialog;
    private javax.swing.JCheckBox chkSelesai;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbPrioritas;
    private javax.swing.JPanel formPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblPrioritas;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spinnerTanggal;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
