/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Agenda;
import model.AgendaManager;
import util.FileManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {
    private AgendaManager manager;
    private DefaultTableModel tableModel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        manager = AgendaManager.getInstance();
        initComponents();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        cardTotalPanel = new javax.swing.JPanel();
        lblTotalTitle = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        lblTotalValue = new javax.swing.JLabel();
        cardSelesaiPanel = new javax.swing.JPanel();
        lblSelesaiTitle = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        lblSelesaiValue = new javax.swing.JLabel();
        cardBelumPanel = new javax.swing.JPanel();
        lblBelumTitle = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        lblBelumValue = new javax.swing.JLabel();
        cardPrioritasPanel = new javax.swing.JPanel();
        lblPrioritasTitle = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        lblPrioritasValue = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        searchFilterPanel = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        lblKategoriCari = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        lblStatusCari = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAgenda = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Agenda Pribadi");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        dashboardPanel.setBackground(new java.awt.Color(236, 240, 241));
        dashboardPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dashboardPanel.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        cardTotalPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardTotalPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219), 2));
        cardTotalPanel.setLayout(new javax.swing.BoxLayout(cardTotalPanel, javax.swing.BoxLayout.Y_AXIS));

        lblTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalTitle.setText("Total Agenda");
        cardTotalPanel.add(lblTotalTitle);
        cardTotalPanel.add(filler1);

        lblTotalValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalValue.setForeground(new java.awt.Color(52, 152, 219));
        lblTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalValue.setText("0");
        cardTotalPanel.add(lblTotalValue);

        dashboardPanel.add(cardTotalPanel);

        cardSelesaiPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardSelesaiPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 174, 96), 2));
        cardSelesaiPanel.setLayout(new javax.swing.BoxLayout(cardSelesaiPanel, javax.swing.BoxLayout.Y_AXIS));

        lblSelesaiTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelesaiTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelesaiTitle.setText("Selesai");
        cardSelesaiPanel.add(lblSelesaiTitle);
        cardSelesaiPanel.add(filler2);

        lblSelesaiValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSelesaiValue.setForeground(new java.awt.Color(39, 174, 96));
        lblSelesaiValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelesaiValue.setText("0");
        cardSelesaiPanel.add(lblSelesaiValue);

        dashboardPanel.add(cardSelesaiPanel);

        cardBelumPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardBelumPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 196, 15), 2));
        cardBelumPanel.setLayout(new javax.swing.BoxLayout(cardBelumPanel, javax.swing.BoxLayout.Y_AXIS));

        lblBelumTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBelumTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBelumTitle.setText("Belum Selesai");
        cardBelumPanel.add(lblBelumTitle);
        cardBelumPanel.add(filler3);

        lblBelumValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBelumValue.setForeground(new java.awt.Color(241, 196, 15));
        lblBelumValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBelumValue.setText("0");
        cardBelumPanel.add(lblBelumValue);

        dashboardPanel.add(cardBelumPanel);

        cardPrioritasPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPrioritasPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60), 2));
        cardPrioritasPanel.setLayout(new javax.swing.BoxLayout(cardPrioritasPanel, javax.swing.BoxLayout.Y_AXIS));

        lblPrioritasTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrioritasTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrioritasTitle.setText("Prioritas Tinggi");
        cardPrioritasPanel.add(lblPrioritasTitle);
        cardPrioritasPanel.add(filler4);

        lblPrioritasValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPrioritasValue.setForeground(new java.awt.Color(231, 76, 60));
        lblPrioritasValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrioritasValue.setText("0");
        cardPrioritasPanel.add(lblPrioritasValue);

        dashboardPanel.add(cardPrioritasPanel);

        getContentPane().add(dashboardPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout(10, 10));

        searchFilterPanel.setBackground(new java.awt.Color(236, 240, 241));
        searchFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PENCARIAN & FILTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        searchFilterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearch.setText("Search");
        searchFilterPanel.add(lblSearch);

        txtSearch.setColumns(25);
        txtSearch.setToolTipText("Cari berdasarkan judul atau deskripsi");
        searchFilterPanel.add(txtSearch);

        btnCari.setBackground(new java.awt.Color(52, 152, 219));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        searchFilterPanel.add(btnCari);
        searchFilterPanel.add(filler5);

        lblKategoriCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKategoriCari.setText("Kategori :");
        searchFilterPanel.add(lblKategoriCari);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Kerja", "Kuliah", "Personal", "Kesehatan" }));
        searchFilterPanel.add(cmbKategori);
        searchFilterPanel.add(filler6);

        lblStatusCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatusCari.setText("Status :");
        searchFilterPanel.add(lblStatusCari);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Selesai", "Belum Selesai" }));
        searchFilterPanel.add(cmbStatus);
        searchFilterPanel.add(filler7);

        btnRefresh.setBackground(new java.awt.Color(149, 165, 166));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        searchFilterPanel.add(btnRefresh);

        centerPanel.add(searchFilterPanel, java.awt.BorderLayout.NORTH);

        tabelAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul", "Tanggal", "Kategori", "Prioritas", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAgenda.setGridColor(new java.awt.Color(189, 195, 199));
        tabelAgenda.setRowHeight(30);
        tabelAgenda.setSelectionBackground(new java.awt.Color(52, 152, 219));
        tabelAgenda.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelAgenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelAgenda.setShowGrid(true);
        jScrollPane1.setViewportView(tabelAgenda);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setBackground(new java.awt.Color(236, 240, 241));
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        btnTambah.setBackground(new java.awt.Color(39, 174, 96));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setToolTipText("Tambah agenda baru (Ctrl+N)");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setPreferredSize(new java.awt.Dimension(160, 40));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        buttonPanel.add(btnTambah);

        btnEdit.setBackground(new java.awt.Color(52, 152, 219));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Edit agenda terpilih");
        btnEdit.setPreferredSize(new java.awt.Dimension(160, 40));
        buttonPanel.add(btnEdit);

        btnHapus.setBackground(new java.awt.Color(231, 76, 60));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Agenda");
        btnHapus.setToolTipText("Hapus agenda terpilih (Del)");
        btnHapus.setPreferredSize(new java.awt.Dimension(160, 40));
        buttonPanel.add(btnHapus);

        btnExport.setBackground(new java.awt.Color(52, 73, 94));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export Data");
        btnExport.setToolTipText("Export ke JSON/TXT");
        btnExport.setPreferredSize(new java.awt.Dimension(160, 40));
        buttonPanel.add(btnExport);

        btnImport.setBackground(new java.awt.Color(52, 73, 94));
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImport.setForeground(new java.awt.Color(255, 255, 255));
        btnImport.setText("Import Data");
        btnImport.setToolTipText("Import dari JSON");
        btnImport.setPreferredSize(new java.awt.Dimension(160, 40));
        buttonPanel.add(btnImport);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>                        

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        TambahAgendaDialog dialog = new TambahAgendaDialog(this, true);
        dialog.setVisible(true);
        loadDataToTable();
        updateDashboard();
    }                                         
    
    private void loadDataToTable() {
        tableModel.setRowCount(0);
        List<Agenda> agendaList = manager.getAllAgenda();
        for (Agenda agenda : agendaList) {
            Object[] row = {
                agenda.getId(),
                agenda.getJudul(),
                agenda.getTanggal(),
                agenda.getKategori(),
                agenda.getPrioritas(),
                agenda.getStatus()
            };
            tableModel.addRow(row);
        }
    }
    
    private void tambahAgenda() {
        TambahAgendaDialog dialog = new TambahAgendaDialog(this, true);
        dialog.setVisible(true);
        loadDataToTable();
    }
    
    private void editAgenda() {
        int selectedRow = tabelAgenda.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih agenda yang akan diedit!");
            return;
        }
        
        String id = tableModel.getValueAt(selectedRow, 0).toString();
        Agenda agenda = manager.getAgendaById(id);
        
        EditAgendaDialog dialog = new EditAgendaDialog(this, true, agenda);
        dialog.setVisible(true);
        loadDataToTable();
    }
    
    private void hapusAgenda() {
        int selectedRow = tabelAgenda.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih agenda yang akan dihapus!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus agenda ini?", 
            "Konfirmasi", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            String id = tableModel.getValueAt(selectedRow, 0).toString();
            manager.hapusAgenda(id);
            loadDataToTable();
            JOptionPane.showMessageDialog(this, "Agenda berhasil dihapus!");
        }
    }
    
    private void cariAgenda() {
        String keyword = txtSearch.getText().trim();
        if (keyword.isEmpty()) {
            loadDataToTable();
            return;
        }
        
        tableModel.setRowCount(0);
        List<Agenda> hasil = manager.searchAgenda(keyword);
        for (Agenda agenda : hasil) {
            Object[] row = {
                agenda.getId(),
                agenda.getJudul(),
                agenda.getTanggal(),
                agenda.getKategori(),
                agenda.getPrioritas(),
                agenda.getStatus()
            };
            tableModel.addRow(row);
        }
    }
    
    private void filterAgenda() {
        String filter = cmbStatus.getSelectedItem().toString();
        tableModel.setRowCount(0);
        List<Agenda> hasil;
        
        switch (filter) {
            case "Semua":
                hasil = manager.getAllAgenda();
                break;
            case "Selesai":
                hasil = manager.filterByStatus(true);
                break;
            case "Belum Selesai":
                hasil = manager.filterByStatus(false);
                break;
            default:
                hasil = manager.filterByKategori(filter);
                break;
        }
        
        for (Agenda agenda : hasil) {
            Object[] row = {
                agenda.getId(),
                agenda.getJudul(),
                agenda.getTanggal(),
                agenda.getKategori(),
                agenda.getPrioritas(),
                agenda.getStatus()
            };
            tableModel.addRow(row);
        }
    }
    
    private void exportData() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export Data");
        
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filepath = fileChooser.getSelectedFile().getAbsolutePath();
            
            String[] options = {"JSON", "TXT"};
            int choice = JOptionPane.showOptionDialog(this,
                "Pilih format export:",
                "Format Export",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
            
            try {
                if (choice == 0) {
                    FileManager.exportToJSON(manager.getAllAgenda(), filepath + ".json");
                } else {
                    FileManager.exportToTXT(manager.getAllAgenda(), filepath + ".txt");
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diexport!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
    }
    
    private void importData() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Import Data");
        
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filepath = fileChooser.getSelectedFile().getAbsolutePath();
            
            try {
                List<Agenda> importedList = FileManager.importFromJSON(filepath);
                manager.setAgendaList(importedList);
                loadDataToTable();
                JOptionPane.showMessageDialog(this, "Data berhasil diimport!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel cardBelumPanel;
    private javax.swing.JPanel cardPrioritasPanel;
    private javax.swing.JPanel cardSelesaiPanel;
    private javax.swing.JPanel cardTotalPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBelumTitle;
    private javax.swing.JLabel lblBelumValue;
    private javax.swing.JLabel lblKategoriCari;
    private javax.swing.JLabel lblPrioritasTitle;
    private javax.swing.JLabel lblPrioritasValue;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSelesaiTitle;
    private javax.swing.JLabel lblSelesaiValue;
    private javax.swing.JLabel lblStatusCari;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JPanel searchFilterPanel;
    private javax.swing.JTable tabelAgenda;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration                   
}
